import { Inter } from "next/font/google";
import { GoogleTagManager } from '@next/third-parties/google'
import "./output.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GoogleTagManager gtmId="AW-11359687580" />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
